<?php

/**
 * @file
 * Contains bars.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bars_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bars module.
    case 'help.page.bars':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bar content type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bars_theme() {
  $theme = [];
  $theme['bar'] = [
    'render element' => 'elements',
    'file' => 'bar.page.inc',
    'template' => 'bar',
  ];
  $theme['bar_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'bar.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function bars_theme_suggestions_bar(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#bar'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'bar__' . $sanitized_view_mode;
  $suggestions[] = 'bar__' . $entity->bundle();
  $suggestions[] = 'bar__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'bar__' . $entity->id();
  $suggestions[] = 'bar__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
